spring:
  datasource:
    url: jdbc:postgresql://db:5432/jsonplaceholder?currentSchema=jsonplaceholder
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: jsonplaceholder
  sql:
    init:
      mode: always

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here-make-it-long-and-secure}
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: TRACE
    com.jsonplaceholder.api: DEBUG
    org.hibernate.SQL: DEBUG 